/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Win32API
 #	author : wford
 #	7/15/2016
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
		case kInitPlugin :
			InitPlugin();
			break;

		case kDeinitPlugin :
			DeinitPlugin();
			break;

// --- Win32API Commands

		case 1 :
			gui_GetWindow( params );
			break;

		case 2 :
			gui_GetWndRect( params );
			break;

		case 3 :
			gui_SetWndRect( params );
			break;

		case 4 :
			gui_ShowWindow( params );
			break;

		case 5 :
			sys_GetUserName( params );
			break;

		case 6 :
			gui_SetWindowTitle( params );
			break;

		case 7 :
			sys_IsMultiByte( params );
			break;

		case 8 :
			gui_DisableCloseBox( params );
			break;

		case 9 :
			gui_SetWindowLong( params );
			break;

		case 10 :
			gui_FlashWindow( params );
			break;

		case 11 :
			gui_WinHelp( params );
			break;

		case 12 :
			sys_GetDefPrinter( params );
			break;

		case 13 :
			sys_SetDefPrinter( params );
			break;

		case 14 :
			sys_EnumPrinters( params );
			break;

		case 15 :
			gui_DelMenuItem( params );
			break;

		case 16 :
			gui_GetOpenFileName( params );
			break;

		case 17 :
			gui_GetSaveFileName( params );
			break;

		case 18 :
			gui_LoadIcon( params );
			break;

		case 19 :
			gui_SetIcon( params );
			break;

		case 20 :
			gui_GetWindowFrom4DWin( params );
			break;

		case 21 :
			sys_GetRegionSettings( params );
			break;

		case 22 :
			sys_GetTimeZone( params );
			break;

		case 23 :
			sys_GetUTCOffset( params );
			break;

		case 24 :
			gui_GetDisplayFontDPI( params );
			break;

		case 25 :
			sys_GetOneRegionSetting( params );
			break;

		case 26 :
			sys_GetPrintJob( params );
			break;

		case 27 :
			sys_GetGUID( params );
			break;

		case 28 :
			sys_GetRoutes( params );
			break;

		case 29 :
			sys_GetNetworkInfo( params );
			break;

		case 30 :
			sys_GetOSVersion( params );
			break;

		case 31 :
			sys_PlayWav( params );
			break;

		case 32 :
			sys_GetWindowMetrics( params );
			break;

		case 33 :
			gui_LoadBackground( params );
			break;

		case 34 :
			sys_SetClientTime( params );
			break;

		case 35 :
			sys_SetClientDate( params );
			break;

		case 36 :
			gui_ToolTipCreate( params );
			break;

		case 37 :
			gui_ToolTipShowOnObject( params );
			break;

		case 38 :
			gui_ToolTipShowOnCoord( params );
			break;

		case 39 :
			gui_ToolTipHide( params );
			break;

		case 40 :
			gui_ToolTipDestroyControl( params );
			break;

		case 41 :
			gui_SetTrayIcon( params );
			break;

		case 42 :
			sys_FileCheck( params );
			break;

		case 43 :
			sys_GetCommandLine( params );
			break;

		case 44 :
			gui_RestrictWindow( params );
			break;

		case 45 :
			gui_GetWindowStyle( params );
			break;

		case 46 :
			gui_GetWindowState( params );
			break;

		case 47 :
			gui_SubClassInit( params );
			break;

		case 48 :
			sys_ShellExecute( params );
			break;

		case 49 :
			sys_IsAppLoaded( params );
			break;

		case 50 :
			gui_SelectColor( params );
			break;

		case 51 :
			gui_RespectToolBar( params );
			break;

		case 52 :
			sys_IsConnectedToInternet( params );
			break;

		case 53 :
			gui_GetSysColor( params );
			break;

		case 54 :
			gui_SetSysColor( params );
			break;

		case 55 :
			sys_GetEnv( params );
			break;

		case 56 :
			sys_SetEnv( params );
			break;

		case 57 :
			sys_GetRegText( params );
			break;

		case 58 :
			sys_GetRegLongint( params );
			break;

		case 59 :
			sys_GetRegArray( params );
			break;

		case 60 :
			sys_GetRegBlob( params );
			break;

		case 61 :
			sys_GetRegType( params );
			break;

		case 62 :
			sys_GetRegEnum( params );
			break;

		case 63 :
			sys_GetDocumentList( params );
			break;

		case 64 :
			sys_SetPluginLanguage( params );
			break;

		case 65 :
			gui_SetWindowStyle( params );
			break;

		case 66 :
			sys_FileExists( params );
			break;

		case 67 :
			sys_DirectoryExists( params );
			break;

		case 68 :
			sys_PrintDirect2Driver( params );
			break;

		case 69 :
			sys_KillProcessByName( params );
			break;

		case 70 :
			sys_KillProcessByID( params );
			break;

		case 71 :
			sys_EnumProcesses( params );
			break;

		case 72 :
			sys_LogonUser( params );
			break;

		case 73 :
			sys_GetTimeZoneList( params );
			break;

		case 74 :
			TWAIN_GetSources( params );
			break;

		case 75 :
			TWAIN_SetSource( params );
			break;

		case 76 :
			TWAIN_AcquireImage( params );
			break;

		case 77 :
			sys_IsAppFrontmost( params );
			break;

		case 78 :
			gui_MessageBox( params );
			break;

		case 79 :
			gui_SetMDIOpaque( params );
			break;

		case 80 :
			gui_SetMDITransparent( params );
			break;

		case 81 :
			gui_HideTaskBar( params );
			break;

		case 82 :
			gui_ShowTaskBar( params );
			break;

		case 83 :
			gui_HideTitleBar( params );
			break;

		case 84 :
			gui_ShowTitleBar( params );
			break;

		case 85 :
			gui_MaximizeMDI( params );
			break;

		case 86 :
			gui_RestoreMDI( params );
			break;

		case 87 :
			gui_MinimizeMDI( params );
			break;

		case 88 :
			sys_DisableTaskManager( params );
			break;

		case 89 :
			sys_EnableTaskManager( params );
			break;

		case 90 :
			sys_SetRegText( params );
			break;

		case 91 :
			sys_SetRegLongint( params );
			break;

		case 92 :
			sys_SetRegArray( params );
			break;

		case 93 :
			sys_SetRegBLOB( params );
			break;

		case 94 :
			sys_IsAppRunningAsService( params );
			break;

		case 95 :
			sys_CompareBLOBs( params );
			break;

		case 96 :
			sys_GetFileVersionInfo( params );
			break;

		case 97 :
			sys_DeleteRegKey( params );
			break;

		case 98 :
			sys_DeleteRegValue( params );
			break;

		case 99 :
			sys_SendRawPrinterData( params );
			break;

		case 100 :
			sys_EncryptAES( params );
			break;

		case 101 :
			sys_DecryptAES( params );
			break;
		
		case 102 :
			gui_TakeScreenshot( params );
			break;

		case 103 :
			gui_ServerUnloadBackground( params );
			break;

		case 104 :
			sys_SetRegQWORD( params );
			break;

		case 105 :
			gui_FreeHandle( params );
			break;

		case 106 :
			gui_FreeAllHandles( params );
			break;

		case 107 :
			gui_GetWindowEx( params );
			break;

		case 108 :
			gui_GetWindowFrom4DWinEx( params );
			break;

		case 109 :
			gui_SetForegroundWindow ( params );
			break;

		case 110 :
			gui_GetWndRectEx( params );
			break;

		case 111 :
			gui_SetWndRectEx( params );
			break;

		case 112 :
			gui_ShowWindowEx( params );
			break;

		case 113 :
			gui_SetWindowTitleEx( params );
			break;

		case 114 :
			gui_DisableCloseBoxEx( params );
			break;

		case 115 :
			gui_SetWindowLongEx( params );
			break;

		case 116 :
			gui_DelMenuItemEx( params );
			break;

		case 117 :
			gui_LoadIconEx( params );
			break;

		case 118 :
			gui_SetIconEx( params );
			break;

		case 119 :
			gui_MessageBoxEx( params );
			break;

		case 120 :
			gui_TakeScreenshotEx( params );
			break;

		case 121 :
			gui_SetForegroundWindowEx( params );
			break;

		case 122 :
			gui_GetWindowStyleEx( params );
			break;

		case 123 :
			gui_RestrictWindowEx( params );
			break;

		case 124 :
			gui_GetWindowStateEx( params );
			break;

		case 125 :
			gui_SetWindowStyleEx( params );
			break;

		case 126 :
			gui_ToolTipCreateEx( params );
			break;

		case 127 :
			gui_ToolTipShowOnObjectEx( params );
			break;

		case 128 :
			gui_FlashWindowEx( params );
			break;

		case 129 :
			gui_SetFocusEx( params );
			break;

		case 130 :
			sys_EncryptFile( params );
			break;

		case 131 :
			sys_DecryptFile( params );
			break;

		case 132 :
			sys_HashText( params );
			break;

		case 133 :
			sys_GetDiskFreeSpace( params );
			break;

		case 134 :
			sys_ProcessStart( params );
			break;

	}
}

void InitPlugin()
{
	// write initialisation code here...
}

void DeinitPlugin()
{
	// write deinitialisation code here...
}

// ------------------------------- Win32API Commands ------------------------------


void gui_GetWindow( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of gui_GetWindow here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWndRect( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 Param6;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetLongParameter( params, 6 );

	// --- write the code of gui_GetWndRect here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_SetLongParameter( params, 3, Param3 );
	PA_SetLongParameter( params, 4, Param4 );
	PA_SetLongParameter( params, 5, Param5 );
	PA_ReturnLong( params, returnValue );
}

void gui_SetWndRect( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 Param6;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetLongParameter( params, 6 );

	// --- write the code of gui_SetWndRect here...

	PA_ReturnLong( params, returnValue );
}

void gui_ShowWindow( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_ShowWindow here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetUserName( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_GetUserName here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowTitle( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of gui_SetWindowTitle here...

	PA_ReturnLong( params, returnValue );
}

void sys_IsMultiByte( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_IsMultiByte here...

	PA_ReturnLong( params, returnValue );
}

void gui_DisableCloseBox( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_DisableCloseBox here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowLong( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_SetWindowLong here...

	PA_ReturnLong( params, returnValue );
}

void gui_FlashWindow( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_FlashWindow here...

	PA_ReturnLong( params, returnValue );
}

void gui_WinHelp( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_WinHelp here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetDefPrinter( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_GetDefPrinter here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_SetDefPrinter( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_SetDefPrinter here...

	PA_ReturnLong( params, returnValue );
}

void sys_EnumPrinters( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_EnumPrinters here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_ReturnLong( params, returnValue );
}

void gui_DelMenuItem( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of gui_DelMenuItem here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetOpenFileName( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_Unichar* Param5_uchars;
	PA_Unistring* Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_long32 Param7;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );
	Param5 = PA_GetStringParameter( params, 5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param7 = PA_GetLongParameter( params, 7 );

	// --- write the code of gui_GetOpenFileName here...

	PA_SetUnistring( Param5, Param5_uchars );
	PA_SetUnistring( Param6, Param6_uchars );
	PA_ReturnLong( params, returnValue );
}

void gui_GetSaveFileName( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_Unichar* Param5_uchars;
	PA_Unistring* Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_long32 Param7;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );
	Param5 = PA_GetStringParameter( params, 5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param7 = PA_GetLongParameter( params, 7 );

	// --- write the code of gui_GetSaveFileName here...

	PA_SetUnistring( Param5, Param5_uchars );
	PA_SetUnistring( Param6, Param6_uchars );
	PA_ReturnLong( params, returnValue );
}

void gui_LoadIcon( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_LoadIcon here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_ReturnLong( params, returnValue );
}

void gui_SetIcon( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_SetIcon here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowFrom4DWin( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_GetWindowFrom4DWin here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetRegionSettings( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_Variable Param2;

	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetVariableParameter( params, 2 );

	// --- write the code of sys_GetRegionSettings here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_SetVariableParameter( params, 2, Param2, 1 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetTimeZone( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of sys_GetTimeZone here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_SetUnistring( Param2, Param2_uchars );
	PA_SetLongParameter( params, 3, Param3 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetUTCOffset( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of sys_GetUTCOffset here...

	PA_SetLongParameter( params, 1, Param1 );
	PA_ReturnLong( params, returnValue );
}

void gui_GetDisplayFontDPI( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_GetDisplayFontDPI here...

	PA_SetLongParameter( params, 1, Param1 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetOneRegionSetting( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_GetOneRegionSetting here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_GetPrintJob( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_GetPrintJob here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetGUID( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_GetGUID here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_SetUnistring( Param2, Param2_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_GetRoutes( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );

	// --- write the code of sys_GetRoutes here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetNetworkInfo( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_GetNetworkInfo here...

	PA_SetUnistring( Param1, Param1_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_GetOSVersion( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_GetOSVersion here...

	PA_SetLongParameter( params, 1, Param1 );
	PA_SetUnistring( Param2, Param2_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_PlayWav( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_PlayWav here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetWindowMetrics( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of sys_GetWindowMetrics here...

	PA_ReturnLong( params, returnValue );
}

void gui_LoadBackground( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_LoadBackground here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetClientTime( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_SetClientTime here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetClientDate( PA_PluginParameters params )
{
	PA_Date Param1;

	PA_long32 Param2;
	PA_long32 returnValue;

	PA_GetDateParameter( params, 1, &Param1.fDay, &Param1.fMonth, &Param1.fYear );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_SetClientDate here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipCreate( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_ToolTipCreate here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipShowOnObject( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_Unichar* Param5_uchars;
	PA_Unistring* Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_long32 Param7;
	PA_long32 Param8;
	PA_long32 Param9;
	PA_long32 Param10;
	PA_long32 Param11;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetStringParameter( params, 5 );
	Param5_uchars = PA_GetUnistring( Param5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param6_uchars = PA_GetUnistring( Param6 );
	Param7 = PA_GetLongParameter( params, 7 );
	Param8 = PA_GetLongParameter( params, 8 );
	Param9 = PA_GetLongParameter( params, 9 );
	Param10 = PA_GetLongParameter( params, 10 );
	Param11 = PA_GetLongParameter( params, 11 );

	// --- write the code of gui_ToolTipShowOnObject here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipShowOnCoord( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_Unichar* Param7_uchars;
	PA_Unistring* Param7;
	PA_long32 Param8;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param6_uchars = PA_GetUnistring( Param6 );
	Param7 = PA_GetStringParameter( params, 7 );
	Param7_uchars = PA_GetUnistring( Param7 );
	Param8 = PA_GetLongParameter( params, 8 );

	// --- write the code of gui_ToolTipShowOnCoord here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipHide( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_ToolTipHide here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipDestroyControl( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_ToolTipDestroyControl here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetTrayIcon( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_Unichar* Param7_uchars;
	PA_Unistring* Param7;
	PA_Unichar* Param8_uchars;
	PA_Unistring* Param8;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param6_uchars = PA_GetUnistring( Param6 );
	Param7 = PA_GetStringParameter( params, 7 );
	Param7_uchars = PA_GetUnistring( Param7 );
	Param8 = PA_GetStringParameter( params, 8 );
	Param8_uchars = PA_GetUnistring( Param8 );

	// --- write the code of gui_SetTrayIcon here...

	PA_ReturnLong( params, returnValue );
}

void sys_FileCheck( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_FileCheck here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetCommandLine( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_GetCommandLine here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_ReturnLong( params, returnValue );
}

void gui_RestrictWindow( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_RestrictWindow here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowStyle( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Variable Param2;

	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetVariableParameter( params, 2 );

	// --- write the code of gui_GetWindowStyle here...

	PA_SetVariableParameter( params, 2, Param2, 1 );
	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowState( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_GetWindowState here...

	PA_ReturnLong( params, returnValue );
}

void gui_SubClassInit( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_SubClassInit here...

	PA_ReturnLong( params, returnValue );
}

void sys_ShellExecute( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_ShellExecute here...

	PA_ReturnLong( params, returnValue );
}

void sys_IsAppLoaded( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_IsAppLoaded here...

	PA_ReturnLong( params, returnValue );
}

void gui_SelectColor( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_SelectColor here...

	PA_SetLongParameter( params, 1, Param1 );
	PA_SetLongParameter( params, 2, Param2 );
	PA_SetLongParameter( params, 3, Param3 );
	PA_SetLongParameter( params, 5, Param5 );
	PA_ReturnLong( params, returnValue );
}

void gui_RespectToolBar( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of gui_RespectToolBar here...

	PA_ReturnLong( params, returnValue );
}

void sys_IsConnectedToInternet( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of sys_IsConnectedToInternet here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetSysColor( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_GetSysColor here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_SetLongParameter( params, 3, Param3 );
	PA_SetLongParameter( params, 4, Param4 );
	PA_ReturnLong( params, returnValue );
}

void gui_SetSysColor( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_SetSysColor here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetEnv( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_GetEnv here...

	PA_SetUnistring( Param2, Param2_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_SetEnv( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_SetEnv here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetRegText( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetRegText here...

	PA_SetUnistring( Param4, Param4_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_GetRegLongint( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetRegLongint here...

	PA_SetLongParameter( params, 4, Param4 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetRegArray( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Variable Param4;

	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetVariableParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetRegArray here...

	PA_SetVariableParameter( params, 4, Param4, 1 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetRegBlob( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Handle Param4;

	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetBlobHandleParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetRegBlob here...

	PA_SetBlobHandleParameter( params, 4, Param4 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetRegType( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_GetRegType here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetRegEnum( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Variable Param3;

	PA_Variable Param4;

	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetVariableParameter( params, 3 );
	Param4 = PA_GetVariableParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetRegEnum here...

	PA_SetVariableParameter( params, 3, Param3, 1 );
	PA_SetVariableParameter( params, 4, Param4, 1 );
	PA_ReturnLong( params, returnValue );
}

void sys_GetDocumentList( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Variable Param3;

	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 Param6;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetVariableParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetLongParameter( params, 6 );

	// --- write the code of sys_GetDocumentList here...

	PA_SetVariableParameter( params, 3, Param3, 1 );
	PA_SetLongParameter( params, 4, Param4 );
	PA_ReturnLong( params, returnValue );
}

void sys_SetPluginLanguage( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of sys_SetPluginLanguage here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowStyle( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_SetWindowStyle here...

	PA_ReturnLong( params, returnValue );
}

void sys_FileExists( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_FileExists here...

	PA_ReturnLong( params, returnValue );
}

void sys_DirectoryExists( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of sys_DirectoryExists here...

	PA_ReturnLong( params, returnValue );
}

void sys_PrintDirect2Driver( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_PrintDirect2Driver here...

	PA_ReturnLong( params, returnValue );
}

void sys_KillProcessByName( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of sys_KillProcessByName here...

	PA_ReturnLong( params, returnValue );
}

void sys_KillProcessByID( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_KillProcessByID here...

	PA_ReturnLong( params, returnValue );
}

void sys_EnumProcesses( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_Variable Param2;

	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetVariableParameter( params, 2 );

	// --- write the code of sys_EnumProcesses here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_SetVariableParameter( params, 2, Param2, 1 );
	PA_ReturnLong( params, returnValue );
}

void sys_LogonUser( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_LogonUser here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetTimeZoneList( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );

	// --- write the code of sys_GetTimeZoneList here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_ReturnLong( params, returnValue );
}

void TWAIN_GetSources( PA_PluginParameters params )
{
	PA_Variable Param1;

	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetVariableParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of TWAIN_GetSources here...

	PA_SetVariableParameter( params, 1, Param1, 1 );
	PA_ReturnLong( params, returnValue );
}

void TWAIN_SetSource( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of TWAIN_SetSource here...

	PA_ReturnLong( params, returnValue );
}

void TWAIN_AcquireImage( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of TWAIN_AcquireImage here...

	PA_ReturnLong( params, returnValue );
}

void sys_IsAppFrontmost( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of sys_IsAppFrontmost here...

	PA_ReturnLong( params, returnValue );
}

void gui_MessageBox( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_MessageBox here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetMDIOpaque( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_SetMDIOpaque here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetMDITransparent( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_SetMDITransparent here...

	PA_ReturnLong( params, returnValue );
}

void gui_HideTaskBar( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_HideTaskBar here...

	PA_ReturnLong( params, returnValue );
}

void gui_ShowTaskBar( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_ShowTaskBar here...

	PA_ReturnLong( params, returnValue );
}

void gui_HideTitleBar( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_HideTitleBar here...

	PA_ReturnLong( params, returnValue );
}

void gui_ShowTitleBar( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_ShowTitleBar here...

	PA_ReturnLong( params, returnValue );
}

void gui_MaximizeMDI( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_MaximizeMDI here...

	PA_ReturnLong( params, returnValue );
}

void gui_RestoreMDI( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_RestoreMDI here...

	PA_ReturnLong( params, returnValue );
}

void gui_MinimizeMDI( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_MinimizeMDI here...

	PA_ReturnLong( params, returnValue );
}

void sys_DisableTaskManager( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of sys_DisableTaskManager here...

	PA_ReturnLong( params, returnValue );
}

void sys_EnableTaskManager( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of sys_EnableTaskManager here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetRegText( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );

	// --- write the code of sys_SetRegText here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetRegLongint( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of sys_SetRegLongint here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetRegArray( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Variable Param4;

	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetVariableParameter( params, 4 );

	// --- write the code of sys_SetRegArray here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetRegBLOB( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Handle Param4;

	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetBlobHandleParameter( params, 4 );

	// --- write the code of sys_SetRegBLOB here...

	PA_ReturnLong( params, returnValue );
}

void sys_IsAppRunningAsService( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of sys_IsAppRunningAsService here...

	PA_ReturnLong( params, returnValue );
}

void sys_CompareBLOBs( PA_PluginParameters params )
{
	PA_Handle Param1;

	PA_Handle Param2;

	PA_long32 returnValue;

	Param1 = PA_GetBlobHandleParameter( params, 1 );
	Param2 = PA_GetBlobHandleParameter( params, 2 );

	// --- write the code of sys_CompareBLOBs here...

	PA_ReturnLong( params, returnValue );
}

void sys_GetFileVersionInfo( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );

	// --- write the code of sys_GetFileVersionInfo here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_SetLongParameter( params, 3, Param3 );
	PA_SetLongParameter( params, 4, Param4 );
	PA_SetLongParameter( params, 5, Param5 );
	PA_ReturnLong( params, returnValue );
}

void sys_DeleteRegKey( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_DeleteRegKey here...

	PA_ReturnLong( params, returnValue );
}

void sys_DeleteRegValue( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_DeleteRegValue here...

	PA_ReturnLong( params, returnValue );
}

void sys_SendRawPrinterData( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_SendRawPrinterData here...

	PA_ReturnLong( params, returnValue );
}

void sys_EncryptAES( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* returnValue_uchars;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_EncryptAES here...

	PA_ReturnString( params, returnValue_uchars );
}

void sys_DecryptAES( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* returnValue_uchars;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_DecryptAES here...

	PA_ReturnString( params, returnValue_uchars );
}

void gui_TakeScreenshot( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of gui_TakeScreenshot here...

	PA_ReturnLong( params, returnValue );
}

void gui_ServerUnloadBackground( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_ServerUnloadBackground here...

	PA_ReturnLong( params, returnValue );
}

void sys_SetRegQWORD( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of sys_SetRegQWORD here...

	PA_ReturnLong( params, returnValue );
}

void gui_FreeHandle( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_FreeHandle here...

	PA_ReturnLong( params, returnValue );
}

void gui_FreeAllHandles( PA_PluginParameters params )
{
	PA_long32 returnValue;

	// --- write the code of gui_FreeAllHandles here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowEx( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );

	// --- write the code of gui_GetWindowEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowFrom4DWinEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_GetWindowFrom4DWinEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetForegroundWindow( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_SetForegroundWindow here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWndRectEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 Param6;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetLongParameter( params, 6 );

	// --- write the code of gui_GetWndRectEx here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_SetLongParameter( params, 3, Param3 );
	PA_SetLongParameter( params, 4, Param4 );
	PA_SetLongParameter( params, 5, Param5 );
	PA_ReturnLong( params, returnValue );
}

void gui_SetWndRectEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 Param5;
	PA_long32 Param6;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetLongParameter( params, 5 );
	Param6 = PA_GetLongParameter( params, 6 );

	// --- write the code of gui_SetWndRectEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_ShowWindowEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_ShowWindowEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowTitleEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of gui_SetWindowTitleEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_DisableCloseBoxEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_DisableCloseBoxEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowLongEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_SetWindowLongEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_DelMenuItemEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );

	// --- write the code of gui_DelMenuItemEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_LoadIconEx( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_LoadIconEx here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_ReturnLong( params, returnValue );
}

void gui_SetIconEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_SetIconEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_MessageBoxEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_MessageBoxEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_TakeScreenshotEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of gui_TakeScreenshotEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetForegroundWindowEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_SetForegroundWindowEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowStyleEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Variable Param2;

	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetVariableParameter( params, 2 );

	// --- write the code of gui_GetWindowStyleEx here...

	PA_SetVariableParameter( params, 2, Param2, 1 );
	PA_ReturnLong( params, returnValue );
}

void gui_RestrictWindowEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_RestrictWindowEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_GetWindowStateEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_GetWindowStateEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetWindowStyleEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_SetWindowStyleEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipCreateEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of gui_ToolTipCreateEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_ToolTipShowOnObjectEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_Unichar* Param5_uchars;
	PA_Unistring* Param5;
	PA_Unichar* Param6_uchars;
	PA_Unistring* Param6;
	PA_long32 Param7;
	PA_long32 Param8;
	PA_long32 Param9;
	PA_long32 Param10;
	PA_long32 Param11;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );
	Param5 = PA_GetStringParameter( params, 5 );
	Param5_uchars = PA_GetUnistring( Param5 );
	Param6 = PA_GetStringParameter( params, 6 );
	Param6_uchars = PA_GetUnistring( Param6 );
	Param7 = PA_GetLongParameter( params, 7 );
	Param8 = PA_GetLongParameter( params, 8 );
	Param9 = PA_GetLongParameter( params, 9 );
	Param10 = PA_GetLongParameter( params, 10 );
	Param11 = PA_GetLongParameter( params, 11 );

	// --- write the code of gui_ToolTipShowOnObjectEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_FlashWindowEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 Param2;
	PA_long32 Param3;
	PA_long32 Param4;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetLongParameter( params, 3 );
	Param4 = PA_GetLongParameter( params, 4 );

	// --- write the code of gui_FlashWindowEx here...

	PA_ReturnLong( params, returnValue );
}

void gui_SetFocusEx( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );

	// --- write the code of gui_SetFocusEx here...

	PA_ReturnLong( params, returnValue );
}

void sys_EncryptFile( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );

	// --- write the code of sys_EncryptFile here...

	PA_ReturnLong( params, returnValue );
}

void sys_DecryptFile( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_Unichar* Param4_uchars;
	PA_Unistring* Param4;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );
	Param4 = PA_GetStringParameter( params, 4 );
	Param4_uchars = PA_GetUnistring( Param4 );

	// --- write the code of sys_DecryptFile here...

	PA_ReturnLong( params, returnValue );
}

void sys_HashText( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_Unichar* Param3_uchars;
	PA_Unistring* Param3;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );
	Param3 = PA_GetStringParameter( params, 3 );
	Param3_uchars = PA_GetUnistring( Param3 );

	// --- write the code of sys_HashText here...

	PA_SetUnistring( Param3, Param3_uchars );
	PA_ReturnLong( params, returnValue );
}

void sys_GetDiskFreeSpace( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_long32 Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetLongParameter( params, 2 );

	// --- write the code of sys_GetDiskFreeSpace here...

	PA_SetLongParameter( params, 2, Param2 );
	PA_ReturnLong( params, returnValue );
}

void sys_ProcessStart( PA_PluginParameters params )
{
	PA_Unichar* Param1_uchars;
	PA_Unistring* Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetStringParameter( params, 1 );
	Param1_uchars = PA_GetUnistring( Param1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of sys_ProcessStart here...

	PA_ReturnLong( params, returnValue );
}

